build:
	pio run --environment esp32-provisioning

monitor:
	pio run --target monitor -e esp32-provisioning

uploadfw:
	pio run --target upload -e esp32-provisioning

uploadfs:
	pio run --target uploadfs --environment esp32-provisioning
